### ISSUE TITLE
Úkol č.2 bez bonusu

### ISSUE THREAD

**Issue by HelenaHanackova** [HelenaHanackova/python_kurz_2022#2]
https://github.com/HelenaHanackova/python_kurz_2022/blob/main/ukol_02.py

Ahoj,
posílám 2. úkol (zatím - uvidím podle času a inspirace :D) bez bonusu.
Docela jsem s tím bojovala (hlavně s tím výpisem textu "neznámý region", abych to tam neměla x-krát), tak snad to aspoň trochu dává smysl.

**Comment by M-Kovar** [comment]
Ahoj Helčo, super, funguje to, takže dobrá práce. A klaním se Tvému použití list comprehension, které jsme se oficiálně ještě neučili:). Je to elegantní způsob, jak rychle projet celý slovník/seznam, a v budoucnu se Ti určitě bude hodit.

Mám jen návrh na vylepšení z pohledu efektivity/optimalizace a zároveň ukázku alternativního řešení: Slovník se tady musí projíždět dvakrát (jednou v ifu, podruhé ve foru). Zpoždění nepoznáme, i tak se to zpracuje bleskurychle, ale pro násobně víc dat už by to třeba mohlo trvat zbytečně dlouho. Proto je dobré se zamyslet, jestli neexistuje nějaké optimálnější řešení, kde proběhne celkově méně cyklů. Samozřejmě pořád lepší to vyřešit neoptimálně než vůbec - píšu to hlavně v zájmu budování správných návyků:). Státy můžeme "optimálněji" vyřešit následovně:
```
zadani = input("Zadej region: ")
staty_v_regionu = []
for stat in staty:
    if zadani == stat["region"]:
        staty_v_regionu.append(stat)
        print(stat["name"])
if not staty_v_regionu:
    print("Neznámý region")
```
... Projíždím slovník (celkově jen jednou) a rovnou si do seznamu sbírám státy ze zvoleného regionu. V případě neznámého regionu se mi nic neprintuje a seznam zůstane prázdný. Ifem pak kouknu, jestli je seznam prázdný - pokud ano, znamená to neznámý region. A dokonce pak posbírané státy můžeš rovnou využít i pro bonusový úkol:).

Když budeš mít čas a inspiraci, klidně pak přidej bonus, napiš další komentář a já se na to podívám.

**Comment by M-Kovar** [comment]
Doplnění k té části "A dokonce pak posbírané státy můžeš rovnou využít i pro bonusový úkol": Napadá mě, že to je jedna z možností, tzn. ze získaného seznamu pak dodatečně posčítat populace subregionu. Ale druhá a efektivnější možnost je populaci subregionu přidat rovnou do toho prvního foru. Každopádně tohle je jen poznámka na okraj, nenech se zmást a řeš podle sebe - třeba vymyslíš něco úplně nového, co mě ani nenapadlo:).
