### ISSUE TITLE
Úkol č.2 (bez bonusu)

### ISSUE THREAD

**Issue by HelenaHanackova** [HelenaHanackova/python_kurz_2022#3]
Ahoj,
posílám hotový úkol: https://github.com/HelenaHanackova/python_kurz_2022/blob/main/ukol_03.py

**Comment by M-Kovar** [comment]
Ahoj Helčo, vypadá to funkčně a návrhy ze slacku jsi zapracovala na jedničku, takže dobrá práce a úkol splněn:). Mám k tomu ještě následující:
- Funkce se pro přehlednost a ze zvyku píšou na začátek souboru (hned po `import ...`), takže doporučuju `input` přesunout až pod ně.
- Doporučuju mírně přebudovat funkci `cena_zpravy()`, aby brala jako vstup text zprávy a měla v sobě zabudovanou cenu 3 Kč a počítání segmentů: Samozřejmě záleží na kontextu a požadavcích, ale přijde mi to tak logičtější. Celé se to pak bude používat (a případně přepoužívat jinde) jednodušeji. Já vím, psal jsem na slacku, ať funkce slouží jen jednomu účelu a je jednoduchá, takže si za to můžu sám:D. Ale tady ten "jasný účel" chápu jako zjištění ceny zprávy, takže se mi to tak zdá výhodnější - v tomto případě je lepší, když vše potřebné zabalíme do jedné funkce, ať to pak nepřekáží jinde.

**Comment by HelenaHanackova** [comment]
Ahoj,
díky za poznámky. Zkusila jsem předělat tu funkci cena_zpravy(), ale nevím, jestli je to tak, jak jsi myslel. Kdyžtak to ještě zkusím předělat znovu.
![obrázek_2022-10-13_193047831](https://user-images.githubusercontent.com/114013114/195665701-c4b05148-cbe7-418d-8707-42a9232aadad.png)

**Comment by HelenaHanackova** [comment]
Ahoj, 
díky za poznámky. Zkusila jsem předělat tu funkci cena_zpravy(), ale nevím, jestli tak, jak jsi měl na mysli. Kdyžtak zkusím ještě znovu.
![ukol_03 oprava](https://user-images.githubusercontent.com/114013114/195666026-c24e1de9-0b32-478b-91fc-3bb6ded4ad05.png)

**Comment by M-Kovar** [comment]
Krása, teď už je to dokonalé:). Myslím, že tuhle appku můžeš rovnou prodat třeba T-Mobilu :D

**Comment by HelenaHanackova** [comment]
:D :D :-D

**Comment by HelenaHanackova** [comment]
:D :D :D
