### ISSUE TITLE
Úkol č.4 /bez bonusu/

### ISSUE THREAD

**Issue by HelenaHanackova** [HelenaHanackova/python_kurz_2022#4]
Ahoj,
hotový úkol je tu: https://github.com/HelenaHanackova/python_kurz_2022/blob/main/ukol_04.py

**Comment by M-Kovar** [comment]
Ahoj Helčo, dobrá práce, všechno funguje podle zadání a ani k tomu nemám žádné poznámky. Píšu splněno a budu se těšit na případný bonus:).
