### ISSUE TITLE
Úkol č.4 - bonus

### ISSUE THREAD

**Issue by HelenaHanackova** [HelenaHanackova/python_kurz_2022#6]
Ahoj,
tak pokus o vyřešení bonusu ke 4. úkolu tady: https://github.com/HelenaHanackova/python_kurz_2022/blob/main/ukol_04_bonus.py

**Comment by M-Kovar** [comment]
Ahoj, super, funguje to a chválím využití volání `__str__()` v `__repr__()`, čímž se ušetří opakování kódu, které programátoři tak moc nemají rádi:).
