### ISSUE TITLE
Úkol č.8 (+bonus)

### ISSUE THREAD

**Issue by HelenaHanackova** [HelenaHanackova/python_kurz_2022#9]
Ahoj,
posílám další úkol: https://github.com/HelenaHanackova/python_kurz_2022/blob/main/ukol_08.ipynb
Ten poslední bod mi nefunguje, nepřišla jsem na to proč. A pak mi ještě nebyla jasná ta poznámka v uvozovkách v tom mém notebooku ze zadání úkolu, takže jsem to nějak odignorovala :D
Díky

**Comment by M-Kovar** [comment]
Ahoj Helčo, dobrá práce, pěkně připravený notebook, píšu splněno:). Pár poznámek:
- Pro zajímavost, výpis jména zvířete v češtině i angličtině jde napsat i kombinací iloc s názvy sloupce: `adopce_zvirat.iloc[34][["nazev_cz","nazev_en"]]`
- K té odignorované poznámce: Jde o to, že některé metody změní přímo objekt, na kterém jsou volané, zatímco jiné vrátí nový objekt a ten původní nechají nezměněný. Zrovna `sort_index()` vrací nový, na což právě upozorňuje ta poznámka. Takže když zavoláš `adopce_zvirat.sort_index()`, vznikne nová tabulka (seřazená), ale původní se nezmění - tím pádem je potřeba si tu novou uložit. Buď do nové proměnné (třeba `adopce_zvirat_sorted = adopce_zvirat.sort_index()`), nebo přepsat původní dataframe (tzn. `adopce_zvirat = adopce_zvirat.sort_index()`), jak říká poznámka.
- ... A představ si, že tohle zrovna způsobuje onen problém s posledním bodem :D. V `adopce_zvirat` pořád zůstává neseřazená tabulka, na které pak nefunguje výběr řádků mezi dvěma želvími indexy. Abys takhle mohla indexovat, musí být dataframe seřazený podle abecedy... což asi celkem dává smysl, protože jinak pandas nevědí, jaká je mezi těmi dvěma želvími indexy posloupnost a návaznost.

Jinak není co řešit. Za odměnu dostáváš outloně:)...
![202917538-84be29c0-4b2a-4272-aae5-7e289b98ca38 1](https://user-images.githubusercontent.com/7311525/204023055-2285e412-678b-472b-a35c-ff2e098a2b20.png)

**Comment by HelenaHanackova** [comment]
Ahoj,
ten outloň je teda super! :D
Aha, aha, díky moc za vysvětlení!
